-- =============================================================================
-- shaw_setup.sql -- SHAW manual-test schema bootstrap for Valdo Engine v3.
--
-- GENERATED FILE. Source of truth: scripts/build_shaw_test_files.py.
-- Edit the generator, re-run it, and commit both fixture + SQL together.
--
-- Purpose
--   1. Six SHAW_* staging tables (placeholder shape) seeded with synthetic
--      rows so file_to_staging gate smoke checks have data to read.
--   2. Seven EXPECTED_*_TBL reconciliation tables (one per TRANERT record
--      type plus BATCH_HEADER) seeded with one row per detail row of
--      tests/manual/fixtures/tranert_shaw_test_valid.txt -- the L2b
--      comparator should report ZERO violations against that fixture.
--
-- Apply with:
--   sqlplus app_int/<pwd>@localhost:1521/FREEPDB1 @tests/manual/sql/shaw_setup.sql
-- ...or use the cross-backend runner:
--   python tests/manual/seed_db.py --backend oracle
-- =============================================================================

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR CONTINUE

-- -----------------------------------------------------------------------------
-- 1) SHAW_* staging tables (placeholder shape -- see TEST_PLAN.md Section 0).
-- -----------------------------------------------------------------------------

CREATE TABLE SHAW_COLLATERAL (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SHAW_FEE_MASTER (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SHAW_LOAN_MASTER (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SHAW_LOANS_NAME (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SHAW_TRANSACTIONS (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SHAW_TRANS_MASTER (
    BATCH_DATE  DATE,
    RECORD_KEY  VARCHAR2(50),
    LINE_NO     NUMBER,
    RAW_LINE    VARCHAR2(4000),
    LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 2) EXPECTED_*_TBL reconciliation tables.
-- One table per TRANERT record type; columns derived from each mapping
-- JSON's `target_name` / `data_type` / `length`. Identifiers starting
-- with a digit (e.g. 10_98_RPT_IND_COD, 24_CYC_DLQ_*_CBRS) are
-- double-quoted -- required by Oracle.
-- -----------------------------------------------------------------------------

CREATE TABLE EXPECTED_BATCH_HEADER_TBL (
    BK_NUM_BRT          NUMBER(5),
    APP_BRT             NUMBER(3),
    EFF_DAT_BRT         DATE,
    TRN_COD_BRT         VARCHAR2(5),
    BAT_NUM_BRT         NUMBER(7),
    INP_SRC_COD_BRT     NUMBER(3),
    BAT_TYP_BRT         NUMBER(2),
    OPR_ID_BRT          VARCHAR2(8),
    ORG_LVL_NUM_1_BRT   NUMBER(7),
    ORG_LVL_NUM_2_BRT   NUMBER(7),
    ORG_LVL_NUM_3_BRT   NUMBER(7),
    ORG_LVL_NUM_4_BRT   NUMBER(7),
    ORG_LVL_NUM_5_BRT   NUMBER(7),
    ORG_LVL_NUM_6_BRT   NUMBER(7),
    ORG_LVL_NUM_7_BRT   NUMBER(7),
    ORG_LVL_NUM_8_BRT   NUMBER(7),
    ORG_LVL_NUM_9_BRT   NUMBER(7),
    ORG_LVL_NUM_10_BRT  NUMBER(7),
    ORG_LVL_NUM_11_BRT  NUMBER(7),
    ORG_LVL_NUM_12_BRT  NUMBER(7),
    ITM_CNT_BRT         NUMBER(9),
    DR_CR_AMT_BRT       NUMBER(22)
);

CREATE TABLE EXPECTED_NEW1_TBL (
    BK_NUM_ERT          NUMBER(5),
    APP_ERT             NUMBER(3),
    LN_NUM_ERT          VARCHAR2(18),
    REF_NUM_ERT         VARCHAR2(3),
    FILLER              VARCHAR2(130),
    EFF_DAT_ERT         DATE,
    TRN_COD_ERT         NUMBER(5),
    BAT_ITM_NUM_ERT     NUMBER(9),
    INP_SRC_COD_ERT     NUMBER(3),
    TRN_CNT_ERT         NUMBER(3),
    TRN_MOR_DTA_FLG_ERT VARCHAR2(1),
    SEL_ID_NEW          VARCHAR2(1),
    LCT_COD_NEW1        VARCHAR2(6),
    USR_ID_NEW1         VARCHAR2(8)
);

CREATE TABLE EXPECTED_CUS_TBL (
    BK_NUM_ERT                    NUMBER(5),
    APP_ERT                       NUMBER(3),
    LN_NUM_ERT                    VARCHAR2(18),
    REF_NUM_ERT                   VARCHAR2(3),
    FILLER                        VARCHAR2(130),
    EFF_DAT_ERT                   DATE,
    TRN_COD_ERT                   NUMBER(5),
    BAT_ITM_NUM_ERT               NUMBER(9),
    INP_SRC_COD_ERT               NUMBER(3),
    TRN_CNT_ERT                   NUMBER(3),
    TRN_MOR_DTA_FLG_ERT           VARCHAR2(1),
    CIF_ACT_NUM_CUS               VARCHAR2(24),
    CIF_ACT_COD_CUS               VARCHAR2(1),
    CIF_CBR_RPT_IND_CUS           VARCHAR2(1),
    CIF_CSM_INF_IND_CUS           VARCHAR2(2),
    DAT_BKY_REC_CUS               DATE,
    CIF_ACT_COD_DES_CUS           VARCHAR2(18),
    CIF_REF_NUM_CUS               VARCHAR2(3),
    LAS_CSM_INF_IND_CUS           VARCHAR2(2),
    ECOA_CODE_CUS                 VARCHAR2(1),
    LAST_ECOA_CODE_CUS            VARCHAR2(1),
    LAST_BUREAU_RECORDED_DATE_CUS DATE,
    FINAL_REPORT_INDICATOR_CUS    VARCHAR2(1),
    LAST_REPORTED_SEG_TYPE_CUS    VARCHAR2(2),
    LAST_CHEX_RECORDED_DATE_CUS   DATE,
    ACTION_CODE                   VARCHAR2(1),
    CONTACT_ID                    VARCHAR2(24),
    LOCATION_CODE                 VARCHAR2(6),
    ACCT_NUM                      VARCHAR2(18),
    NAME_RELATIONSHIP             VARCHAR2(1),
    LEAD_CONTACT_IND              NUMBER(1),
    RESPONSIBLE_PARTY             NUMBER(1),
    CAS_ADDRESS_IND               VARCHAR2(1),
    EXTERNAL_SYSTEM_ID            VARCHAR2(4),
    PREFERRED_CURRENCY            VARCHAR2(3)
);

CREATE TABLE EXPECTED_ORI_TBL (
    BK_NUM_ERT             NUMBER(5),
    APP_ERT                NUMBER(3),
    LN_NUM_ERT             VARCHAR2(18),
    REF_NUM_ERT            VARCHAR2(3),
    FILLER                 VARCHAR2(130),
    EFF_DAT_ERT            DATE,
    TRN_COD_ERT            NUMBER(5),
    BAT_ITM_NUM_ERT        NUMBER(9),
    INP_SRC_COD_ERT        NUMBER(3),
    TRN_CNT_ERT            NUMBER(3),
    TRN_MOR_DTA_FLG_ERT    VARCHAR2(1),
    OGL_CONTRACT_DAT_ORI   DATE,
    OGL_TRM_ORI            NUMBER(3),
    OGL_MAT_DAT_ORI        DATE,
    OGL_CONTRACT_AMT_ORI   NUMBER(22),
    OGL_PORTFOLIO_TYP_ORI  VARCHAR2(1),
    LN_TYP_ORI             NUMBER(3),
    COF_CDN_IND_ORI        NUMBER(1),
    OGL_NTE_DAT_ORI        DATE,
    OGL_NTE_AMT_ORI        NUMBER(22),
    OGL_COF_INT_AMT_ORI    NUMBER(22),
    INT_RT_ORI             NUMBER(7),
    OGL_INT_RT_ORI         NUMBER(7),
    REP_TYP_ORI            NUMBER(3),
    HGH_BAL_ORI            NUMBER(22),
    AMT_PAS_DUE_30_ORI     NUMBER(22),
    AMT_PAS_DUE_60_ORI     NUMBER(22),
    AMT_PAS_DUE_90_ORI     NUMBER(22),
    AMT_PAS_DUE_120_ORI    NUMBER(22),
    OGL_NUM_PMT_MTD_ORI    NUMBER(5),
    OGL_NUM_PMT_YTD_ORI    NUMBER(5),
    OGL_NUM_PMT_LTD_ORI    NUMBER(5),
    OGL_PMT_AMT_MTD_ORI    NUMBER(22),
    OGL_PMT_AMT_YTD_ORI    NUMBER(22),
    OGL_PMT_AMT_LTD_ORI    NUMBER(22),
    FIL_FLD_ORI            VARCHAR2(3),
    COF_REA_COD_ORI        VARCHAR2(3),
    ST_COD_ORI             VARCHAR2(3),
    DAT_INT_ACR_TO_ORI     DATE,
    ACT_STA_ORI            NUMBER(1),
    MTG_AGC_ID_ORI         VARCHAR2(2),
    PCOF_DAT_LAS_PMT_ORI   DATE,
    MTG_ID_NUM_ORI         VARCHAR2(18),
    DAT_LAS_STM_ORI        DATE,
    PCOF_PMT_AMT_LAS_ORI   NUMBER(22),
    CNV_ACT_NUM_ORI        VARCHAR2(20),
    OGL_PMT_AMT_ORI        NUMBER(22),
    DAT_ACT_CLS_TO_ATY_ORI DATE
);

CREATE TABLE EXPECTED_COD_TBL (
    BK_NUM_ERT               NUMBER(5),
    APP_ERT                  NUMBER(3),
    LN_NUM_ERT               VARCHAR2(18),
    REF_NUM_ERT              VARCHAR2(3),
    FILLER                   VARCHAR2(130),
    EFF_DAT_ERT              DATE,
    TRN_COD_ERT              NUMBER(5),
    BAT_ITM_NUM_ERT          NUMBER(9),
    INP_SRC_COD_ERT          NUMBER(3),
    TRN_CNT_ERT              NUMBER(3),
    TRN_MOR_DTA_FLG_ERT      VARCHAR2(1),
    STP_ACR_ATY_COD_COD      NUMBER(1),
    DAT_PLC_IN_STP_COD       DATE,
    DAT_STP_ACR_RMD_COD      DATE,
    INT_ACR_WHI_STP_COD      NUMBER(22),
    LGL_STA_COD_COD          VARCHAR2(3),
    DAT_LAS_RPO_COD          DATE,
    RPO_COD_COD              NUMBER(1),
    DUE_DAT_DAY_COD          NUMBER(2),
    DAT_RMD_RPO_COD          DATE,
    FCL_STA_IND_COD          VARCHAR2(1),
    ORG_LVL_NUM_1_COD        NUMBER(7),
    ORG_LVL_NUM_2_COD        NUMBER(7),
    ORG_LVL_NUM_3_COD        NUMBER(7),
    ORG_LVL_NUM_4_COD        NUMBER(7),
    ORG_LVL_NUM_5_COD        NUMBER(7),
    ORG_LVL_NUM_6_COD        NUMBER(7),
    ORG_LVL_NUM_7_COD        NUMBER(7),
    ORG_LVL_NUM_8_COD        NUMBER(7),
    ORG_LVL_NUM_9_COD        NUMBER(7),
    ORG_LVL_NUM_10_COD       NUMBER(7),
    ORG_LVL_NUM_11_COD       NUMBER(7),
    ORG_LVL_NUM_12_COD       NUMBER(7),
    "10_98_RPT_IND_COD"      VARCHAR2(1),
    LCE_GEO_COD_COD          VARCHAR2(9),
    CR_RT_COD                VARCHAR2(4),
    CAL_RPT_COD_COD          VARCHAR2(4),
    OGL_LN_POO_NUM_COD       NUMBER(7),
    OGL_LN_OFC_COD           VARCHAR2(9),
    LN_OFC_CUR_COD           VARCHAR2(9),
    OGL_BR_NUM_COD           NUMBER(6),
    LN_PUR_COD_COD           VARCHAR2(3),
    LN_CAT_COD               NUMBER(3),
    DLR_NUM_COD              NUMBER(7),
    FCL_EFF_DAT_COD          DATE,
    STM_FRQ_COD              VARCHAR2(1),
    NATL_CURRENCY_COD        VARCHAR2(3),
    PREF_CURRENCY_COD        VARCHAR2(3),
    BASE_CURRENCY_COD        VARCHAR2(3),
    PRT_COF_BK_NUM_COD       NUMBER(5),
    PRT_COF_APP_COD          NUMBER(3),
    PRT_COF_LN_NUM_COD       VARCHAR2(18),
    NAS_SRC_COD_COD          NUMBER(3),
    HMDA_ULI_CODE            VARCHAR2(45),
    IRS_PROP_SECURE_TYPE_COD VARCHAR2(8),
    IRS_PROP_ADDR_DESC_COD   VARCHAR2(39),
    IRS_NUM_OF_MORT_COD      NUMBER(4)
);

CREATE TABLE EXPECTED_CBRS_TBL (
    BK_NUM_ERT             NUMBER(5),
    APP_ERT                NUMBER(3),
    LN_NUM_ERT             VARCHAR2(18),
    REF_NUM_ERT            VARCHAR2(3),
    FILLER                 VARCHAR2(130),
    EFF_DAT_ERT            DATE,
    TRN_COD_ERT            NUMBER(5),
    BAT_ITM_NUM_ERT        NUMBER(9),
    INP_SRC_COD_ERT        NUMBER(3),
    TRN_CNT_ERT            NUMBER(3),
    TRN_MOR_DTA_FLG_ERT    VARCHAR2(1),
    DAT_DLQ_STR_CBRS       DATE,
    M2F_CMT_COD_CBRS       VARCHAR2(2),
    HGH_DAY_DLQ_CBRS       NUMBER(5),
    M2F_CMP_CON_COD_CBRS   VARCHAR2(2),
    HGH_AMT_DLQ_CBRS       NUMBER(22),
    PRE_COF_L1_NUM_CBRS    VARCHAR2(30),
    "24_CYC_DLQ_01_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_12_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_23_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_02_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_13_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_24_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_03_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_14_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_25_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_04_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_15_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_05_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_16_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_06_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_17_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_07_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_18_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_08_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_19_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_09_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_20_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_10_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_21_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_11_CBRS"   VARCHAR2(1),
    "24_CYC_DLQ_22_CBRS"   VARCHAR2(1),
    ACT_TYP_CBRS           VARCHAR2(3),
    LAS_LN_BAL_CBRS        NUMBER(22),
    LAS_DAT_RPT_CBRS       DATE,
    LAS_ACT_STA_CBRS       VARCHAR2(2),
    LAS_CMT_COD_CBRS       VARCHAR2(2),
    LAS_CMP_COD_CBRS       VARCHAR2(2),
    CUR_PMT_RTG_CBRS       VARCHAR2(1),
    PET_DAT_CBRS           DATE,
    PET_ACT_STA_CBRS       VARCHAR2(2),
    PET_SCH_PMT_AMT_CBRS   NUMBER(22),
    PET_CUR_BAL_CBRS       NUMBER(22),
    PET_AMT_PAS_DUE_CBRS   NUMBER(22),
    PET_PMT_RTG_CBRS       VARCHAR2(1),
    CHX_RTG_TRN_NUM_CBRS   VARCHAR2(9),
    CHX_ACT_NUM_CBRS       VARCHAR2(20),
    CHX_ACT_TYP_CBRS       VARCHAR2(3),
    CHX_REA_COD_1_CBRS     VARCHAR2(2),
    CHX_REA_COD_2_CBRS     VARCHAR2(2),
    CHX_REA_COD_3_CBRS     VARCHAR2(2),
    CHX_DIS_IND_CBRS       VARCHAR2(1),
    CHX_LAS_DAT_RPT_CBRS   DATE,
    CHX_LAS_REA_RPT_CBRS   VARCHAR2(2),
    CHX_LAS_CLO_STA_CBRS   VARCHAR2(2),
    SEC_LAS_DAT_RPT_CBRS   DATE,
    SEC_LN_NUM_CBRS        VARCHAR2(30),
    SEC_LAS_ACT_STA_CBRS   VARCHAR2(2),
    SEC_LAS_LN_BAL_CBRS    NUMBER(22)
);

CREATE TABLE EXPECTED_REC_TBL (
    BK_NUM_ERT          NUMBER(5),
    APP_ERT             NUMBER(3),
    LN_NUM_ERT          VARCHAR2(18),
    REF_NUM_ERT         VARCHAR2(3),
    FILLER              VARCHAR2(130),
    EFF_DAT_ERT         DATE,
    TRN_COD_ERT         NUMBER(5),
    BAT_ITM_NUM_ERT     NUMBER(9),
    INP_SRC_COD_ERT     NUMBER(3),
    TRN_CNT_ERT         NUMBER(3),
    TRN_MOR_DTA_FLG_ERT VARCHAR2(1),
    RCF_REF_NUM_REC     VARCHAR2(3),
    RCF_FEE_DES_REC     VARCHAR2(30),
    RCF_AMT_REC         NUMBER(22),
    RCF_PCT_REC         NUMBER(7),
    RCF_ASE_COD_REC     NUMBER(1),
    RCF_INT_IND_REC     NUMBER(1),
    RCF_MAX_FEE_AMT_REC NUMBER(22),
    RCF_DES_COD_REC     NUMBER(3),
    RCF_MAX_FEE_LTD_REC NUMBER(22),
    RCF_FEE_WVE_IND_REC VARCHAR2(1),
    RCF_OGL_AMT_REC     NUMBER(22),
    EXP_PYF_IND_REC     VARCHAR2(1),
    RCF_ICR_COD_REC     NUMBER(1),
    CST_DFC_IND_REC     VARCHAR2(1),
    CMB_PMT_PTY_REC     NUMBER(3),
    RCF_DUE_REC         NUMBER(22),
    FCL_CST_PD_YTD_REC  NUMBER(22),
    RCF_CAP_LTD_REC     NUMBER(22),
    RCF_ASE_MTD_REC     NUMBER(22),
    RCF_PD_MTD_REC      NUMBER(22),
    RCF_ASE_YTD_REC     NUMBER(22),
    RCF_PD_YTD_REC      NUMBER(22),
    RCF_ASE_LTD_REC     NUMBER(22),
    RCF_PD_LTD_REC      NUMBER(22)
);


-- -----------------------------------------------------------------------------
-- 3) Seed -- SHAW_* staging tables (5 synthetic rows each).
-- -----------------------------------------------------------------------------

INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'COLL-0001', 1, 'COLL-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'COLL-0002', 2, 'COLL-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'COLL-0003', 3, 'COLL-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'COLL-0004', 4, 'COLL-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'COLL-0005', 5, 'COLL-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'FEE-0001', 1, 'FEE-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'FEE-0002', 2, 'FEE-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'FEE-0003', 3, 'FEE-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'FEE-0004', 4, 'FEE-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'FEE-0005', 5, 'FEE-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                    ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LOAN-0001', 1, 'LOAN-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LOAN-0002', 2, 'LOAN-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LOAN-0003', 3, 'LOAN-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LOAN-0004', 4, 'LOAN-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LOAN-0005', 5, 'LOAN-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LNAM-0001', 1, 'LNAM-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LNAM-0002', 2, 'LNAM-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LNAM-0003', 3, 'LNAM-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LNAM-0004', 4, 'LNAM-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'LNAM-0005', 5, 'LNAM-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRNS-0001', 1, 'TRNS-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRNS-0002', 2, 'TRNS-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRNS-0003', 3, 'TRNS-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRNS-0004', 4, 'TRNS-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRNS-0005', 5, 'TRNS-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRMS-0001', 1, 'TRMS-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRMS-0002', 2, 'TRMS-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRMS-0003', 3, 'TRMS-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRMS-0004', 4, 'TRMS-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES (DATE '2026-06-01', 'TRMS-0005', 5, 'TRMS-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');

-- -----------------------------------------------------------------------------
-- 4) Seed -- EXPECTED_*_TBL (one row per detail row in tranert_shaw_test_valid.txt).
--    Counts: BATCH_HEADER=1, NEW1=3, CUS=4, ORI=2, COD=2, CBRS=2, REC=2.
--    Multi-account fixture: 3 accounts at 2 banks (BK 040 x2 + BK 041 x1).
-- -----------------------------------------------------------------------------

INSERT INTO EXPECTED_BATCH_HEADER_TBL (BK_NUM_BRT, APP_BRT, EFF_DAT_BRT, TRN_COD_BRT, BAT_NUM_BRT, INP_SRC_COD_BRT, BAT_TYP_BRT, OPR_ID_BRT, ORG_LVL_NUM_1_BRT, ORG_LVL_NUM_2_BRT, ORG_LVL_NUM_3_BRT, ORG_LVL_NUM_4_BRT, ORG_LVL_NUM_5_BRT, ORG_LVL_NUM_6_BRT, ORG_LVL_NUM_7_BRT, ORG_LVL_NUM_8_BRT, ORG_LVL_NUM_9_BRT, ORG_LVL_NUM_10_BRT, ORG_LVL_NUM_11_BRT, ORG_LVL_NUM_12_BRT, ITM_CNT_BRT, DR_CR_AMT_BRT) VALUES (40, 1, DATE '2026-06-01', 'BATCH', 1, 1, 32, 'VALDOTST', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32005, '998', 'P', 'A');
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32005, '997', 'B', 'B');
INSERT INTO EXPECTED_ORI_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32010);
INSERT INTO EXPECTED_COD_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32025);
INSERT INTO EXPECTED_CBRS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32040);
INSERT INTO EXPECTED_REC_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000010001    ', DATE '2026-06-01', 32075);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000020001    ', DATE '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, '00100000020001    ', DATE '2026-06-01', 32005, '998', 'P', 'A');
INSERT INTO EXPECTED_ORI_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, '00100000020001    ', DATE '2026-06-01', 32010);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, '00100000030001    ', DATE '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (41, 1, '00100000030001    ', DATE '2026-06-01', 32005, '998', 'P', 'A');
INSERT INTO EXPECTED_COD_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, '00100000030001    ', DATE '2026-06-01', 32025);
INSERT INTO EXPECTED_CBRS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, '00100000030001    ', DATE '2026-06-01', 32040);
INSERT INTO EXPECTED_REC_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, '00100000030001    ', DATE '2026-06-01', 32075);

COMMIT;


-- -----------------------------------------------------------------------------
-- Optional teardown -- uncomment as a block to reset between runs.
-- -----------------------------------------------------------------------------
-- DROP TABLE EXPECTED_REC_TBL PURGE;
-- DROP TABLE EXPECTED_CBRS_TBL PURGE;
-- DROP TABLE EXPECTED_COD_TBL PURGE;
-- DROP TABLE EXPECTED_ORI_TBL PURGE;
-- DROP TABLE EXPECTED_CUS_TBL PURGE;
-- DROP TABLE EXPECTED_NEW1_TBL PURGE;
-- DROP TABLE EXPECTED_BATCH_HEADER_TBL PURGE;
-- DROP TABLE SHAW_TRANS_MASTER PURGE;
-- DROP TABLE SHAW_TRANSACTIONS PURGE;
-- DROP TABLE SHAW_LOANS_NAME PURGE;
-- DROP TABLE SHAW_LOAN_MASTER PURGE;
-- DROP TABLE SHAW_FEE_MASTER PURGE;
-- DROP TABLE SHAW_COLLATERAL PURGE;

EXIT

