-- =============================================================================
-- shaw_setup_sqlite.sql -- Oracle-free SHAW manual-test schema for Valdo v3.
--
-- GENERATED FILE. Source of truth: scripts/build_shaw_test_files.py.
--
-- Apply with:
--   sqlite3 tests/manual/valdo_test.db < tests/manual/sql/shaw_setup_sqlite.sql
-- ...or, preferred (handles --drop-first, prints summary):
--   python tests/manual/seed_db.py --backend sqlite
--
-- Type substitutions vs. Oracle:
--   VARCHAR2(N)                -> TEXT          (length ignored in SQLite)
--   NUMBER(N)                  -> INTEGER       (or REAL where needed)
--   DATE                       -> TEXT          (ISO-8601 YYYY-MM-DD)
--   TIMESTAMP DEFAULT SYSTIMESTAMP -> TEXT DEFAULT CURRENT_TIMESTAMP
-- Identifiers that begin with a digit are wrapped in double quotes,
-- same as Oracle. SQLite accepts the same syntax.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) SHAW_* staging tables (placeholder shape).
-- -----------------------------------------------------------------------------

CREATE TABLE SHAW_COLLATERAL (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SHAW_FEE_MASTER (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SHAW_LOAN_MASTER (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SHAW_LOANS_NAME (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SHAW_TRANSACTIONS (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SHAW_TRANS_MASTER (
    BATCH_DATE  TEXT,
    RECORD_KEY  TEXT,
    LINE_NO     INTEGER,
    RAW_LINE    TEXT,
    LOAD_TS     TEXT DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 2) EXPECTED_*_TBL reconciliation tables.
-- -----------------------------------------------------------------------------

CREATE TABLE EXPECTED_BATCH_HEADER_TBL (
    BK_NUM_BRT          INTEGER,
    APP_BRT             INTEGER,
    EFF_DAT_BRT         TEXT,
    TRN_COD_BRT         TEXT,
    BAT_NUM_BRT         INTEGER,
    INP_SRC_COD_BRT     INTEGER,
    BAT_TYP_BRT         INTEGER,
    OPR_ID_BRT          TEXT,
    ORG_LVL_NUM_1_BRT   INTEGER,
    ORG_LVL_NUM_2_BRT   INTEGER,
    ORG_LVL_NUM_3_BRT   INTEGER,
    ORG_LVL_NUM_4_BRT   INTEGER,
    ORG_LVL_NUM_5_BRT   INTEGER,
    ORG_LVL_NUM_6_BRT   INTEGER,
    ORG_LVL_NUM_7_BRT   INTEGER,
    ORG_LVL_NUM_8_BRT   INTEGER,
    ORG_LVL_NUM_9_BRT   INTEGER,
    ORG_LVL_NUM_10_BRT  INTEGER,
    ORG_LVL_NUM_11_BRT  INTEGER,
    ORG_LVL_NUM_12_BRT  INTEGER,
    ITM_CNT_BRT         INTEGER,
    DR_CR_AMT_BRT       REAL
);

CREATE TABLE EXPECTED_NEW1_TBL (
    BK_NUM_ERT          INTEGER,
    APP_ERT             INTEGER,
    LN_NUM_ERT          TEXT,
    REF_NUM_ERT         TEXT,
    FILLER              TEXT,
    EFF_DAT_ERT         TEXT,
    TRN_COD_ERT         INTEGER,
    BAT_ITM_NUM_ERT     INTEGER,
    INP_SRC_COD_ERT     INTEGER,
    TRN_CNT_ERT         INTEGER,
    TRN_MOR_DTA_FLG_ERT TEXT,
    SEL_ID_NEW          TEXT,
    LCT_COD_NEW1        TEXT,
    USR_ID_NEW1         TEXT
);

CREATE TABLE EXPECTED_CUS_TBL (
    BK_NUM_ERT                    INTEGER,
    APP_ERT                       INTEGER,
    LN_NUM_ERT                    TEXT,
    REF_NUM_ERT                   TEXT,
    FILLER                        TEXT,
    EFF_DAT_ERT                   TEXT,
    TRN_COD_ERT                   INTEGER,
    BAT_ITM_NUM_ERT               INTEGER,
    INP_SRC_COD_ERT               INTEGER,
    TRN_CNT_ERT                   INTEGER,
    TRN_MOR_DTA_FLG_ERT           TEXT,
    CIF_ACT_NUM_CUS               TEXT,
    CIF_ACT_COD_CUS               TEXT,
    CIF_CBR_RPT_IND_CUS           TEXT,
    CIF_CSM_INF_IND_CUS           TEXT,
    DAT_BKY_REC_CUS               TEXT,
    CIF_ACT_COD_DES_CUS           TEXT,
    CIF_REF_NUM_CUS               TEXT,
    LAS_CSM_INF_IND_CUS           TEXT,
    ECOA_CODE_CUS                 TEXT,
    LAST_ECOA_CODE_CUS            TEXT,
    LAST_BUREAU_RECORDED_DATE_CUS TEXT,
    FINAL_REPORT_INDICATOR_CUS    TEXT,
    LAST_REPORTED_SEG_TYPE_CUS    TEXT,
    LAST_CHEX_RECORDED_DATE_CUS   TEXT,
    ACTION_CODE                   TEXT,
    CONTACT_ID                    TEXT,
    LOCATION_CODE                 TEXT,
    ACCT_NUM                      TEXT,
    NAME_RELATIONSHIP             TEXT,
    LEAD_CONTACT_IND              INTEGER,
    RESPONSIBLE_PARTY             INTEGER,
    CAS_ADDRESS_IND               TEXT,
    EXTERNAL_SYSTEM_ID            TEXT,
    PREFERRED_CURRENCY            TEXT
);

CREATE TABLE EXPECTED_ORI_TBL (
    BK_NUM_ERT             INTEGER,
    APP_ERT                INTEGER,
    LN_NUM_ERT             TEXT,
    REF_NUM_ERT            TEXT,
    FILLER                 TEXT,
    EFF_DAT_ERT            TEXT,
    TRN_COD_ERT            INTEGER,
    BAT_ITM_NUM_ERT        INTEGER,
    INP_SRC_COD_ERT        INTEGER,
    TRN_CNT_ERT            INTEGER,
    TRN_MOR_DTA_FLG_ERT    TEXT,
    OGL_CONTRACT_DAT_ORI   TEXT,
    OGL_TRM_ORI            INTEGER,
    OGL_MAT_DAT_ORI        TEXT,
    OGL_CONTRACT_AMT_ORI   REAL,
    OGL_PORTFOLIO_TYP_ORI  TEXT,
    LN_TYP_ORI             INTEGER,
    COF_CDN_IND_ORI        INTEGER,
    OGL_NTE_DAT_ORI        TEXT,
    OGL_NTE_AMT_ORI        REAL,
    OGL_COF_INT_AMT_ORI    REAL,
    INT_RT_ORI             REAL,
    OGL_INT_RT_ORI         REAL,
    REP_TYP_ORI            INTEGER,
    HGH_BAL_ORI            REAL,
    AMT_PAS_DUE_30_ORI     REAL,
    AMT_PAS_DUE_60_ORI     REAL,
    AMT_PAS_DUE_90_ORI     REAL,
    AMT_PAS_DUE_120_ORI    REAL,
    OGL_NUM_PMT_MTD_ORI    INTEGER,
    OGL_NUM_PMT_YTD_ORI    INTEGER,
    OGL_NUM_PMT_LTD_ORI    INTEGER,
    OGL_PMT_AMT_MTD_ORI    REAL,
    OGL_PMT_AMT_YTD_ORI    REAL,
    OGL_PMT_AMT_LTD_ORI    REAL,
    FIL_FLD_ORI            TEXT,
    COF_REA_COD_ORI        TEXT,
    ST_COD_ORI             TEXT,
    DAT_INT_ACR_TO_ORI     TEXT,
    ACT_STA_ORI            INTEGER,
    MTG_AGC_ID_ORI         TEXT,
    PCOF_DAT_LAS_PMT_ORI   TEXT,
    MTG_ID_NUM_ORI         TEXT,
    DAT_LAS_STM_ORI        TEXT,
    PCOF_PMT_AMT_LAS_ORI   REAL,
    CNV_ACT_NUM_ORI        TEXT,
    OGL_PMT_AMT_ORI        REAL,
    DAT_ACT_CLS_TO_ATY_ORI TEXT
);

CREATE TABLE EXPECTED_COD_TBL (
    BK_NUM_ERT               INTEGER,
    APP_ERT                  INTEGER,
    LN_NUM_ERT               TEXT,
    REF_NUM_ERT              TEXT,
    FILLER                   TEXT,
    EFF_DAT_ERT              TEXT,
    TRN_COD_ERT              INTEGER,
    BAT_ITM_NUM_ERT          INTEGER,
    INP_SRC_COD_ERT          INTEGER,
    TRN_CNT_ERT              INTEGER,
    TRN_MOR_DTA_FLG_ERT      TEXT,
    STP_ACR_ATY_COD_COD      INTEGER,
    DAT_PLC_IN_STP_COD       TEXT,
    DAT_STP_ACR_RMD_COD      TEXT,
    INT_ACR_WHI_STP_COD      REAL,
    LGL_STA_COD_COD          TEXT,
    DAT_LAS_RPO_COD          TEXT,
    RPO_COD_COD              INTEGER,
    DUE_DAT_DAY_COD          INTEGER,
    DAT_RMD_RPO_COD          TEXT,
    FCL_STA_IND_COD          TEXT,
    ORG_LVL_NUM_1_COD        INTEGER,
    ORG_LVL_NUM_2_COD        INTEGER,
    ORG_LVL_NUM_3_COD        INTEGER,
    ORG_LVL_NUM_4_COD        INTEGER,
    ORG_LVL_NUM_5_COD        INTEGER,
    ORG_LVL_NUM_6_COD        INTEGER,
    ORG_LVL_NUM_7_COD        INTEGER,
    ORG_LVL_NUM_8_COD        INTEGER,
    ORG_LVL_NUM_9_COD        INTEGER,
    ORG_LVL_NUM_10_COD       INTEGER,
    ORG_LVL_NUM_11_COD       INTEGER,
    ORG_LVL_NUM_12_COD       INTEGER,
    "10_98_RPT_IND_COD"      TEXT,
    LCE_GEO_COD_COD          TEXT,
    CR_RT_COD                TEXT,
    CAL_RPT_COD_COD          TEXT,
    OGL_LN_POO_NUM_COD       INTEGER,
    OGL_LN_OFC_COD           TEXT,
    LN_OFC_CUR_COD           TEXT,
    OGL_BR_NUM_COD           INTEGER,
    LN_PUR_COD_COD           TEXT,
    LN_CAT_COD               INTEGER,
    DLR_NUM_COD              INTEGER,
    FCL_EFF_DAT_COD          TEXT,
    STM_FRQ_COD              TEXT,
    NATL_CURRENCY_COD        TEXT,
    PREF_CURRENCY_COD        TEXT,
    BASE_CURRENCY_COD        TEXT,
    PRT_COF_BK_NUM_COD       INTEGER,
    PRT_COF_APP_COD          INTEGER,
    PRT_COF_LN_NUM_COD       TEXT,
    NAS_SRC_COD_COD          INTEGER,
    HMDA_ULI_CODE            TEXT,
    IRS_PROP_SECURE_TYPE_COD TEXT,
    IRS_PROP_ADDR_DESC_COD   TEXT,
    IRS_NUM_OF_MORT_COD      INTEGER
);

CREATE TABLE EXPECTED_CBRS_TBL (
    BK_NUM_ERT             INTEGER,
    APP_ERT                INTEGER,
    LN_NUM_ERT             TEXT,
    REF_NUM_ERT            TEXT,
    FILLER                 TEXT,
    EFF_DAT_ERT            TEXT,
    TRN_COD_ERT            INTEGER,
    BAT_ITM_NUM_ERT        INTEGER,
    INP_SRC_COD_ERT        INTEGER,
    TRN_CNT_ERT            INTEGER,
    TRN_MOR_DTA_FLG_ERT    TEXT,
    DAT_DLQ_STR_CBRS       TEXT,
    M2F_CMT_COD_CBRS       TEXT,
    HGH_DAY_DLQ_CBRS       INTEGER,
    M2F_CMP_CON_COD_CBRS   TEXT,
    HGH_AMT_DLQ_CBRS       REAL,
    PRE_COF_L1_NUM_CBRS    TEXT,
    "24_CYC_DLQ_01_CBRS"   TEXT,
    "24_CYC_DLQ_12_CBRS"   TEXT,
    "24_CYC_DLQ_23_CBRS"   TEXT,
    "24_CYC_DLQ_02_CBRS"   TEXT,
    "24_CYC_DLQ_13_CBRS"   TEXT,
    "24_CYC_DLQ_24_CBRS"   TEXT,
    "24_CYC_DLQ_03_CBRS"   TEXT,
    "24_CYC_DLQ_14_CBRS"   TEXT,
    "24_CYC_DLQ_25_CBRS"   TEXT,
    "24_CYC_DLQ_04_CBRS"   TEXT,
    "24_CYC_DLQ_15_CBRS"   TEXT,
    "24_CYC_DLQ_05_CBRS"   TEXT,
    "24_CYC_DLQ_16_CBRS"   TEXT,
    "24_CYC_DLQ_06_CBRS"   TEXT,
    "24_CYC_DLQ_17_CBRS"   TEXT,
    "24_CYC_DLQ_07_CBRS"   TEXT,
    "24_CYC_DLQ_18_CBRS"   TEXT,
    "24_CYC_DLQ_08_CBRS"   TEXT,
    "24_CYC_DLQ_19_CBRS"   TEXT,
    "24_CYC_DLQ_09_CBRS"   TEXT,
    "24_CYC_DLQ_20_CBRS"   TEXT,
    "24_CYC_DLQ_10_CBRS"   TEXT,
    "24_CYC_DLQ_21_CBRS"   TEXT,
    "24_CYC_DLQ_11_CBRS"   TEXT,
    "24_CYC_DLQ_22_CBRS"   TEXT,
    ACT_TYP_CBRS           TEXT,
    LAS_LN_BAL_CBRS        REAL,
    LAS_DAT_RPT_CBRS       TEXT,
    LAS_ACT_STA_CBRS       TEXT,
    LAS_CMT_COD_CBRS       TEXT,
    LAS_CMP_COD_CBRS       TEXT,
    CUR_PMT_RTG_CBRS       TEXT,
    PET_DAT_CBRS           TEXT,
    PET_ACT_STA_CBRS       TEXT,
    PET_SCH_PMT_AMT_CBRS   REAL,
    PET_CUR_BAL_CBRS       REAL,
    PET_AMT_PAS_DUE_CBRS   REAL,
    PET_PMT_RTG_CBRS       TEXT,
    CHX_RTG_TRN_NUM_CBRS   TEXT,
    CHX_ACT_NUM_CBRS       TEXT,
    CHX_ACT_TYP_CBRS       TEXT,
    CHX_REA_COD_1_CBRS     TEXT,
    CHX_REA_COD_2_CBRS     TEXT,
    CHX_REA_COD_3_CBRS     TEXT,
    CHX_DIS_IND_CBRS       TEXT,
    CHX_LAS_DAT_RPT_CBRS   TEXT,
    CHX_LAS_REA_RPT_CBRS   TEXT,
    CHX_LAS_CLO_STA_CBRS   TEXT,
    SEC_LAS_DAT_RPT_CBRS   TEXT,
    SEC_LN_NUM_CBRS        TEXT,
    SEC_LAS_ACT_STA_CBRS   TEXT,
    SEC_LAS_LN_BAL_CBRS    REAL
);

CREATE TABLE EXPECTED_REC_TBL (
    BK_NUM_ERT          INTEGER,
    APP_ERT             INTEGER,
    LN_NUM_ERT          TEXT,
    REF_NUM_ERT         TEXT,
    FILLER              TEXT,
    EFF_DAT_ERT         TEXT,
    TRN_COD_ERT         INTEGER,
    BAT_ITM_NUM_ERT     INTEGER,
    INP_SRC_COD_ERT     INTEGER,
    TRN_CNT_ERT         INTEGER,
    TRN_MOR_DTA_FLG_ERT TEXT,
    RCF_REF_NUM_REC     TEXT,
    RCF_FEE_DES_REC     TEXT,
    RCF_AMT_REC         REAL,
    RCF_PCT_REC         REAL,
    RCF_ASE_COD_REC     INTEGER,
    RCF_INT_IND_REC     INTEGER,
    RCF_MAX_FEE_AMT_REC REAL,
    RCF_DES_COD_REC     INTEGER,
    RCF_MAX_FEE_LTD_REC REAL,
    RCF_FEE_WVE_IND_REC TEXT,
    RCF_OGL_AMT_REC     REAL,
    EXP_PYF_IND_REC     TEXT,
    RCF_ICR_COD_REC     INTEGER,
    CST_DFC_IND_REC     TEXT,
    CMB_PMT_PTY_REC     INTEGER,
    RCF_DUE_REC         REAL,
    FCL_CST_PD_YTD_REC  REAL,
    RCF_CAP_LTD_REC     REAL,
    RCF_ASE_MTD_REC     REAL,
    RCF_PD_MTD_REC      REAL,
    RCF_ASE_YTD_REC     REAL,
    RCF_PD_YTD_REC      REAL,
    RCF_ASE_LTD_REC     REAL,
    RCF_PD_LTD_REC      REAL
);


-- -----------------------------------------------------------------------------
-- 3) Seed -- SHAW_* staging tables (5 synthetic rows each).
-- -----------------------------------------------------------------------------

BEGIN;
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'COLL-0001', 1, 'COLL-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'COLL-0002', 2, 'COLL-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'COLL-0003', 3, 'COLL-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'COLL-0004', 4, 'COLL-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_COLLATERAL (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'COLL-0005', 5, 'COLL-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'FEE-0001', 1, 'FEE-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'FEE-0002', 2, 'FEE-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'FEE-0003', 3, 'FEE-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'FEE-0004', 4, 'FEE-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                    ');
INSERT INTO SHAW_FEE_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'FEE-0005', 5, 'FEE-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                    ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LOAN-0001', 1, 'LOAN-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LOAN-0002', 2, 'LOAN-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LOAN-0003', 3, 'LOAN-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LOAN-0004', 4, 'LOAN-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_LOAN_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LOAN-0005', 5, 'LOAN-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LNAM-0001', 1, 'LNAM-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LNAM-0002', 2, 'LNAM-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LNAM-0003', 3, 'LNAM-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LNAM-0004', 4, 'LNAM-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_LOANS_NAME (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'LNAM-0005', 5, 'LNAM-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRNS-0001', 1, 'TRNS-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRNS-0002', 2, 'TRNS-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRNS-0003', 3, 'TRNS-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRNS-0004', 4, 'TRNS-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_TRANSACTIONS (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRNS-0005', 5, 'TRNS-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRMS-0001', 1, 'TRMS-0001-VALDO-FIXTURE-2026-06-01-LN0000000000000001-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRMS-0002', 2, 'TRMS-0002-VALDO-FIXTURE-2026-06-01-LN0000000000000002-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRMS-0003', 3, 'TRMS-0003-VALDO-FIXTURE-2026-06-01-LN0000000000000003-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRMS-0004', 4, 'TRMS-0004-VALDO-FIXTURE-2026-06-01-LN0000000000000004-PADDING                   ');
INSERT INTO SHAW_TRANS_MASTER (BATCH_DATE, RECORD_KEY, LINE_NO, RAW_LINE) VALUES ('2026-06-01', 'TRMS-0005', 5, 'TRMS-0005-VALDO-FIXTURE-2026-06-01-LN0000000000000005-PADDING                   ');

-- -----------------------------------------------------------------------------
-- 4) Seed -- EXPECTED_*_TBL (one row per detail row in tranert_shaw_test_valid.txt).
--    Counts: BATCH_HEADER=1, NEW1=3, CUS=4, ORI=2, COD=2, CBRS=2, REC=2.
--    Multi-account fixture: 3 accounts at 2 banks (BK 040 x2 + BK 041 x1).
-- -----------------------------------------------------------------------------

INSERT INTO EXPECTED_BATCH_HEADER_TBL (BK_NUM_BRT, APP_BRT, EFF_DAT_BRT, TRN_COD_BRT, BAT_NUM_BRT, INP_SRC_COD_BRT, BAT_TYP_BRT, OPR_ID_BRT, ORG_LVL_NUM_1_BRT, ORG_LVL_NUM_2_BRT, ORG_LVL_NUM_3_BRT, ORG_LVL_NUM_4_BRT, ORG_LVL_NUM_5_BRT, ORG_LVL_NUM_6_BRT, ORG_LVL_NUM_7_BRT, ORG_LVL_NUM_8_BRT, ORG_LVL_NUM_9_BRT, ORG_LVL_NUM_10_BRT, ORG_LVL_NUM_11_BRT, ORG_LVL_NUM_12_BRT, ITM_CNT_BRT, DR_CR_AMT_BRT) VALUES (40, 1, '2026-06-01', 'BATCH', 1, 1, 32, 'VALDOTST', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32005, '999', 'P', 'A');
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32005, '998', 'B', 'B');
INSERT INTO EXPECTED_ORI_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32010);
INSERT INTO EXPECTED_COD_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32025);
INSERT INTO EXPECTED_CBRS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32040);
INSERT INTO EXPECTED_REC_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000010001', '2026-06-01', 32075);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000020001', '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (40, 1, ' 04000100000020001', '2026-06-01', 32005, '999', 'P', 'A');
INSERT INTO EXPECTED_ORI_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (40, 1, ' 04000100000020001', '2026-06-01', 32010);
INSERT INTO EXPECTED_NEW1_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, ' 04100100000030001', '2026-06-01', 32000);
INSERT INTO EXPECTED_CUS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT, CIF_REF_NUM_CUS, CIF_ACT_COD_CUS, NAME_RELATIONSHIP) VALUES (41, 1, ' 04100100000030001', '2026-06-01', 32005, '999', 'P', 'A');
INSERT INTO EXPECTED_COD_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, ' 04100100000030001', '2026-06-01', 32025);
INSERT INTO EXPECTED_CBRS_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, ' 04100100000030001', '2026-06-01', 32040);
INSERT INTO EXPECTED_REC_TBL (BK_NUM_ERT, APP_ERT, LN_NUM_ERT, EFF_DAT_ERT, TRN_COD_ERT) VALUES (41, 1, ' 04100100000030001', '2026-06-01', 32075);
COMMIT;
