"""Create MCP_REVOKED_TOKENS blocklist table for per-token revocation (S9-4, #389).

EF-S7 MCP bearer tokens are HMAC-signed and self-contained — the only
lever to invalidate a leaked token was rotating
``VALDO_MCP_TOKEN_SIGNING_KEY``, which nukes *every* outstanding token,
innocent ones included. S9-4 adds a per-token revocation blocklist keyed
on the token's opaque ``jti`` (added to the token format in the same
story). An admin POSTs a ``jti`` to ``POST /api/v2/mcp/revoke``; the
``jti`` is inserted here; token verification consults this table (via a
60s-TTL in-memory cache) *after* signature validation and rejects any
token whose ``jti`` is present.

Table shape
-----------
- ``jti`` (PK, ``String(64)``) — the opaque 16-byte token id, hex-encoded
  (32 chars today). Wider for headroom, mirroring ``APP_MCP_RUN_REGISTRY``.
- ``reason`` (``String(500)``) — operator-supplied free-text reason for
  the revocation (incident ticket, "laptop stolen", etc.). Audit value.
- ``revoked_by`` (``String(256)``) — the principal (LDAP DN or short user)
  who issued the revocation. SOX attribution.
- ``revoked_at`` (``DateTime``) — when the revocation was recorded.

Cross-dialect design decisions
-------------------------------
- Dialect-agnostic SQLAlchemy generics (``String``, ``DateTime``), same
  approach as migrations 0003/0004. Oracle renders these natively;
  PostgreSQL and SQLite likewise.
- An index on ``revoked_at`` supports a future expiry-sweep job (revoked
  tokens past their own ``expires_at`` no longer need a blocklist row,
  since signature+expiry already rejects them) — not used in S9-4 but
  cheap to add now.
- Idempotent ``upgrade`` (skips when the table already exists, mirrors
  0003/0004). Downgrade is a clean ``DROP TABLE``.

Naming note
-----------
The table is named ``MCP_REVOKED_TOKENS`` (not ``APP_``-prefixed) per the
issue spec. The Alembic ``include_object`` autogenerate filter in
``src/database/db_url.py`` only governs *autogenerated* diffs; this is an
explicit ``op.create_table`` so the name is honoured verbatim.

Revision ID: 0005
Revises: 0004
Create Date: 2026-06-16
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    """Return True if the named table exists in the current schema.

    Args:
        table_name: The table name to look up (case-insensitive match).

    Returns:
        True if the table exists, False otherwise.
    """
    bind = op.get_bind()
    inspector = sa_inspect(bind)
    return table_name.upper() in [t.upper() for t in inspector.get_table_names()]


def upgrade() -> None:
    """Create MCP_REVOKED_TOKENS and its supporting index.

    Idempotent: skipped when the table already exists, so safe to apply
    against an environment where the table was created manually for a
    rehearsal.
    """
    if _table_exists("MCP_REVOKED_TOKENS"):
        return

    op.create_table(
        "MCP_REVOKED_TOKENS",
        sa.Column("jti", sa.String(64), primary_key=True),
        sa.Column("reason", sa.String(500), nullable=True),
        sa.Column("revoked_by", sa.String(256), nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index(
        "IDX_MCP_REVOKED_AT",
        "MCP_REVOKED_TOKENS",
        ["revoked_at"],
    )


def downgrade() -> None:
    """Drop MCP_REVOKED_TOKENS and its index."""
    if not _table_exists("MCP_REVOKED_TOKENS"):
        return
    op.drop_index("IDX_MCP_REVOKED_AT", table_name="MCP_REVOKED_TOKENS")
    op.drop_table("MCP_REVOKED_TOKENS")
