-- CM3 Run History Tables
-- Creates two tables in the CM3INT schema to persist test suite run data.
--
-- When to use:
--   The tool writes run history to reports/run_history.json by default.
--   Create these tables when you want runs to persist across deployments,
--   be queryable by multiple users, or feed into a BI/reporting tool.
--
-- Prerequisites:
--   CM3INT user must have CREATE TABLE privilege.
--   Run as CM3INT or as SYSTEM with: ALTER SESSION SET CURRENT_SCHEMA = CM3INT;
--
-- Usage:
--   sqlplus cm3int/<password>@localhost:1521/FREEPDB1 @sql/cm3int/setup_cm3_run_history.sql
--
-- Idempotent: safe to run multiple times (drops existing tables first).

WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Drop child table first (FK dependency)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CM3INT.CM3_RUN_TESTS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CM3INT.CM3_RUN_HISTORY CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ---------------------------------------------------------------------------
-- CM3_RUN_HISTORY — one row per suite run
-- ---------------------------------------------------------------------------
PROMPT Creating CM3INT.CM3_RUN_HISTORY ...

CREATE TABLE CM3INT.CM3_RUN_HISTORY (
  RUN_ID          VARCHAR2(36)   PRIMARY KEY,          -- UUID from run-tests
  SUITE_NAME      VARCHAR2(200)  NOT NULL,
  ENVIRONMENT     VARCHAR2(100)  NOT NULL,
  RUN_TIMESTAMP   TIMESTAMP      NOT NULL,             -- UTC ISO-8601
  STATUS          VARCHAR2(20)   NOT NULL,             -- PASS | FAIL | PARTIAL
  PASS_COUNT      NUMBER(6)      DEFAULT 0 NOT NULL,
  FAIL_COUNT      NUMBER(6)      DEFAULT 0 NOT NULL,
  SKIP_COUNT      NUMBER(6)      DEFAULT 0 NOT NULL,
  TOTAL_COUNT     NUMBER(6)      DEFAULT 0 NOT NULL,
  REPORT_URL      VARCHAR2(500),                       -- relative URL e.g. /reports/…
  ARCHIVE_PATH    VARCHAR2(1000),                      -- local filesystem path to archive dir
  CREATED_TS      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE  CM3INT.CM3_RUN_HISTORY              IS 'One row per cm3-batch test suite run.';
COMMENT ON COLUMN CM3INT.CM3_RUN_HISTORY.RUN_ID       IS 'UUID generated by run-tests CLI.';
COMMENT ON COLUMN CM3INT.CM3_RUN_HISTORY.STATUS       IS 'PASS=all tests passed, FAIL=all tests failed or errored, PARTIAL=mixed.';
COMMENT ON COLUMN CM3INT.CM3_RUN_HISTORY.ARCHIVE_PATH IS 'Filesystem path to the tamper-evident archive directory for this run.';

-- ---------------------------------------------------------------------------
-- CM3_RUN_TESTS — one row per individual test within a run
-- ---------------------------------------------------------------------------
PROMPT Creating CM3INT.CM3_RUN_TESTS ...

CREATE TABLE CM3INT.CM3_RUN_TESTS (
  TEST_ID         NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RUN_ID          VARCHAR2(36)   NOT NULL,
  TEST_NAME       VARCHAR2(200)  NOT NULL,
  TEST_TYPE       VARCHAR2(50)   NOT NULL,             -- structural | oracle_vs_file | rules | api_check
  STATUS          VARCHAR2(20)   NOT NULL,             -- PASS | FAIL | ERROR | SKIPPED
  ROW_COUNT       NUMBER(12),                          -- rows processed (null for api_check)
  ERROR_COUNT     NUMBER(10)     DEFAULT 0,
  DURATION_SECS   NUMBER(8,2),
  REPORT_PATH     VARCHAR2(1000),                      -- path to per-test HTML report if generated
  CREATED_TS      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RUN_TESTS_RUN FOREIGN KEY (RUN_ID)
    REFERENCES CM3INT.CM3_RUN_HISTORY (RUN_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  CM3INT.CM3_RUN_TESTS             IS 'One row per test within a cm3-batch suite run.';
COMMENT ON COLUMN CM3INT.CM3_RUN_TESTS.TEST_TYPE   IS 'structural | oracle_vs_file | rules | api_check';
COMMENT ON COLUMN CM3INT.CM3_RUN_TESTS.STATUS      IS 'PASS | FAIL | ERROR | SKIPPED';

-- Useful index for querying a specific run's tests
CREATE INDEX CM3INT.IDX_RUN_TESTS_RUN_ID ON CM3INT.CM3_RUN_TESTS (RUN_ID);

-- Useful index for filtering by date range
CREATE INDEX CM3INT.IDX_RUN_HISTORY_TS ON CM3INT.CM3_RUN_HISTORY (RUN_TIMESTAMP);

COMMIT;
PROMPT Done. Tables CM3INT.CM3_RUN_HISTORY and CM3INT.CM3_RUN_TESTS created.
