-- Run as CM3INT user (or with CM3INT. prefixes)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT_CONTACTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CONTACTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE ACCOUNTS (
  ACCOUNT_ID        VARCHAR2(10) PRIMARY KEY,
  CHARGE_OFF_AMT    NUMBER(12,2),
  FIRST_DELQ_DATE   DATE,
  OPENED_DATE       DATE
);

CREATE TABLE CONTACTS (
  CONTACT_ID        VARCHAR2(12) PRIMARY KEY,
  FULL_NAME         VARCHAR2(100)
);

CREATE TABLE ACCOUNT_CONTACTS (
  ACCOUNT_ID        VARCHAR2(10) NOT NULL,
  CONTACT_ID        VARCHAR2(12) NOT NULL,
  RELATIONSHIP_CODE VARCHAR2(20),
  REL_SEQ           NUMBER(3),
  CONSTRAINT PK_ACCOUNT_CONTACTS PRIMARY KEY (ACCOUNT_ID, CONTACT_ID),
  CONSTRAINT FK_ACCT_CONTACTS_ACCT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID),
  CONSTRAINT FK_ACCT_CONTACTS_CONT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID)
);

-- 100 accounts
INSERT INTO ACCOUNTS (ACCOUNT_ID, CHARGE_OFF_AMT, FIRST_DELQ_DATE, OPENED_DATE)
SELECT 'ACCT' || LPAD(LEVEL, 6, '0') AS ACCOUNT_ID,
       ROUND(DBMS_RANDOM.VALUE(500, 20000), 2) AS CHARGE_OFF_AMT,
       DATE '2025-01-01' + LEVEL AS FIRST_DELQ_DATE,
       DATE '2023-12-01' - LEVEL AS OPENED_DATE
FROM DUAL
CONNECT BY LEVEL <= 100;

-- Contact rows: 1..3 per account
INSERT INTO CONTACTS (CONTACT_ID, FULL_NAME)
SELECT 'C' || SUBSTR(a.ACCOUNT_ID, 5) || LPAD(c.seq, 2, '0') AS CONTACT_ID,
       'Customer_' || SUBSTR(a.ACCOUNT_ID, 8) || '_' || c.seq AS FULL_NAME
FROM ACCOUNTS a
JOIN (
  SELECT 1 AS seq FROM DUAL
  UNION ALL SELECT 2 FROM DUAL
  UNION ALL SELECT 3 FROM DUAL
) c
  ON c.seq <= (MOD(TO_NUMBER(SUBSTR(a.ACCOUNT_ID,5)),3) + 1);

INSERT INTO ACCOUNT_CONTACTS (ACCOUNT_ID, CONTACT_ID, RELATIONSHIP_CODE, REL_SEQ)
SELECT a.ACCOUNT_ID,
       'C' || SUBSTR(a.ACCOUNT_ID, 5) || LPAD(c.seq, 2, '0') AS CONTACT_ID,
       CASE WHEN c.seq = 1 THEN 'PRIMARY' ELSE 'SECONDARY' END AS RELATIONSHIP_CODE,
       999 - c.seq AS REL_SEQ
FROM ACCOUNTS a
JOIN (
  SELECT 1 AS seq FROM DUAL
  UNION ALL SELECT 2 FROM DUAL
  UNION ALL SELECT 3 FROM DUAL
) c
  ON c.seq <= (MOD(TO_NUMBER(SUBSTR(a.ACCOUNT_ID,5)),3) + 1);

COMMIT;
