"""Typed dataclass model for a parsed onboarding workbook (EC-S2).

This module defines the single in-memory contract that ferries an onboarding
workbook from the EC-S2 reader (``src/onboarding/workbook_reader.py``) to
the downstream emitters:

    * EC-S3 — source YAML emitter
    * EC-S4 — mapping JSON emitter
    * EC-S5 — rules JSON emitter
    * EC-S6 — ``valdo onboard-source`` CLI orchestrator

By emitting typed, frozen dataclasses (instead of forcing each emitter to
re-parse raw openpyxl rows) the reader guarantees:

    * A single normalisation pass — pipe-separated cells parsed once,
      bool cells coerced once, blank optional cells projected to ``None`` once.
    * Tight cross-reference contracts — ``OutputFileSpec.mapping_sheet``
      is the key the downstream emitter looks up in
      ``OnboardingWorkbook.mapping_sheets``; no string-fuzzing in EC-S4.
    * DASH-style canonical field names preserved verbatim
      (``LN-NUM-ERT`` stays ``LN-NUM-ERT`` — the underscore form is the
      SQL alias and is generated by EC-S4/S5, not the reader).

All dataclasses are ``frozen=True`` so a downstream emitter cannot
accidentally mutate the parsed tree (and so equality is value-based for
unit tests).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

# ---------------------------------------------------------------------------
# Reader-level exception.
# ---------------------------------------------------------------------------


class WorkbookReadError(Exception):
    """Raised by EC-S2 when a workbook is schema-valid but its data
    cannot be coerced into typed dataclasses.

    Distinct from ``WorkbookSchemaError`` (EC-S1):

        * ``WorkbookSchemaError`` — *shape* problems (missing sheet,
          missing column header).
        * ``WorkbookReadError`` — *value* problems (e.g. a bool cell
          contains ``"maybe"`` instead of ``true/false/yes/no/1/0``;
          a required int cell contains a non-numeric string).

    The split lets the BA see distinct remediation hints: schema errors
    are fixed by adding/renaming sheets and columns; read errors are
    fixed by correcting individual cell values.
    """


# ---------------------------------------------------------------------------
# Source sheet — single row of source-wide configuration.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SourceInfo:
    """Source-wide configuration captured from the ``Source`` sheet.

    Attributes:
        source_code: Short uppercase code (``SHAW``, ``SRC_A``).
        schema_version: Source-spec schema version (integer).
        release_tag: Release marker (e.g. ``2026.M06``).
        description: Free-text description; ``""`` if blank.
        staging_schema: Oracle staging schema name (e.g. ``APP_INT``).
        output_root: Filesystem root where generated outputs land.
        java_load_script: Wrapper script invoked by the load gate.
        java_generate_script: Wrapper script invoked by the generate gate;
            ``""`` if the source has no generate phase.
        gate_load_blocking: Whether load-gate failures block the pipeline.
        gate_load_invoke_java: Whether the load gate actually invokes the
            Java wrapper (vs. a dry-run).
        gate_f2s_blocking: Whether file-to-staging failures block the pipeline.
        gate_generate_blocking: Whether generate-gate failures block.
        gate_generate_invoke_java: Whether the generate gate invokes Java.
        gate_l1_blocking: Whether L1 (field-level) failures block.
        gate_l2b_blocking: Whether L2b (reconciliation) failures block.
        gate_l3_blocking: Whether L3 (cross-file) failures block.
        gate_mr_report_blocking: Whether multi-record report failures block.
        expected_table_strategy: How the ED-S3 SQL emitter wraps the
            ``expected_*.sql`` body for restricted Oracle schemas.

            * ``"view"`` (default) — emit the bare ``SELECT`` (engine
              wraps it behind ``CREATE OR REPLACE VIEW`` at run time).
              Preserves ED-S2 behaviour.
            * ``"ctas"`` — wrap as ``CREATE TABLE app_int.EXPECTED_<TOKEN>_TBL
              AS <SELECT> …``  inside an idempotent ``BEGIN EXECUTE
              IMMEDIATE … EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955
              THEN RAISE …`` PL/SQL block (matches the committed
              ``030_expected_tables.sql`` ORA-955 "name already in use"
              trap so re-running the bootstrap is a no-op).
            * ``"ctas_with_drop"`` — prepend a
              ``BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_int.EXPECTED_<TOKEN>_TBL
              PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-942)
              THEN RAISE; END IF; END; /`` block so the CTAS replaces any
              prior copy. ORA-942 = "table or view does not exist".

            Used when the validation user lacks the ``CREATE VIEW``
            system privilege (the cm3int/app_int lockdown case).
    """

    source_code: str
    schema_version: int
    release_tag: str
    description: str
    staging_schema: str
    output_root: str
    java_load_script: str
    java_generate_script: str
    gate_load_blocking: bool
    gate_load_invoke_java: bool
    gate_f2s_blocking: bool
    gate_generate_blocking: bool
    gate_generate_invoke_java: bool
    gate_l1_blocking: bool
    gate_l2b_blocking: bool
    gate_l3_blocking: bool
    gate_mr_report_blocking: bool
    expected_table_strategy: Literal["view", "ctas", "ctas_with_drop"] = "view"


# ---------------------------------------------------------------------------
# Input/output file specs.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InputFileSpec:
    """A single row from the ``InputFiles`` sheet.

    Attributes:
        file_type: Logical file-type identifier (``COLLATERAL_MASTER``).
        glob: Filename pattern (``collateral-master_*.txt``).
        mapping_sheet: Name of the ``*_Mapping`` sheet describing this file.
        target_staging_table: Oracle table name receiving F2S inserts.
        thresholds_max_errors: Max tolerated parse errors; ``None`` means
            the BA left the cell blank (engine default = 0).
    """

    file_type: str
    glob: str
    mapping_sheet: str
    target_staging_table: str
    thresholds_max_errors: int | None


@dataclass(frozen=True)
class OutputFileSpec:
    """A single row from the ``OutputFiles`` sheet.

    Attributes:
        file_type: Logical output-file-type (``ATOCTRAN``, ``CDSTRANS_EFB``).
        glob: Output filename pattern.
        mapping_sheet: Name of the ``*_Mapping`` sheet OR the literal
            string ``"(umbrella)"`` for multi-record outputs.
        rules_sheet: Name of the ``*_Rules`` sheet OR ``"(umbrella)"``
            for multi-record outputs OR ``""`` if no rules apply.
        tolerance_max_errors: Max tolerated L1/L2b errors; ``None`` = blank.
        tolerance_max_error_pct: Max tolerated error rate (0.0-100.0);
            ``None`` = blank.
        tolerance_ignore_fields: Field names to skip during L2b compare.
            ``None`` = blank cell; ``[]`` = explicit empty list (not used).
    """

    file_type: str
    glob: str
    mapping_sheet: str
    rules_sheet: str
    tolerance_max_errors: int | None
    tolerance_max_error_pct: float | None
    tolerance_ignore_fields: list[str] | None

    @property
    def is_multi_record(self) -> bool:
        """Whether this output is a multi-record umbrella (no flat mapping)."""
        return self.mapping_sheet == "(umbrella)"


# ---------------------------------------------------------------------------
# Multi-record sheets.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class MultiRecordRow:
    """One record-type entry inside a ``MultiRecord_<FILETYPE>`` sheet.

    Attributes:
        record_type_name: Stable identifier (``batch_header``, ``rt_32000``).
        discriminator_field: DASH-style field name carrying the type code.
        discriminator_position: 1-indexed character position (fixed-width).
        discriminator_length: Character length of the discriminator field.
        match_kind: ``position_first`` (first row in file), or
            ``discriminator_equals`` (single value), or
            ``discriminator_in`` (comma-joined value list — split by EC-S4).
        match_value: Raw match value. For ``discriminator_in`` this is a
            comma-joined list parsed downstream by the emitter; for
            ``position_first`` this is the literal ``"first"``.
        mapping_sheet: Name of the per-record-type ``*_Mapping`` sheet.
        rules_sheet: Name of the per-record-type ``*_Rules`` sheet; ``""``
            if this record type has no rules.
        cardinality: Whether this record type appears once or many times
            per driver row, or is optional.
    """

    record_type_name: str
    discriminator_field: str
    discriminator_position: int
    discriminator_length: int
    match_kind: Literal["position_first", "discriminator_equals", "discriminator_in"]
    match_value: str
    mapping_sheet: str
    rules_sheet: str
    cardinality: Literal[
        "one_per_driver_row", "many_per_driver_row", "zero_or_one_per_driver_row"
    ]


@dataclass(frozen=True)
class MultiRecordSheet:
    """A complete ``MultiRecord_<FILETYPE>`` sheet.

    Attributes:
        file_type: Extracted from the sheet name suffix (``TRANERT``).
        rows: Ordered list of record-type rows as they appear in the sheet.
    """

    file_type: str
    rows: list[MultiRecordRow]


# ---------------------------------------------------------------------------
# Reconciliation sheets.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ReconciliationRow:
    """One reconciliation entry inside a ``Reconciliation_<FILETYPE>`` sheet.

    Per the EC-S1 convention, the ``assertions`` cell on the FIRST data row
    carries file-wide assertions and is lifted to
    :attr:`ReconciliationSheet.file_wide_assertions`; it is therefore NOT
    repeated on this row-level dataclass.

    Attributes:
        record_type_name: Matches a row in the corresponding
            ``MultiRecord_<FILETYPE>`` sheet, or ``"(flat)"`` when the
            output file is not multi-record.
        key_columns: DASH-style field names forming the row-match key.
            Always a list (``[]`` for blank), never ``None``.
        staging_table: Oracle table name holding the expected rows;
            ``""`` when the engine derives it from the file-type default.
        predicate: Free-text SQL predicate added to the staging query;
            ``""`` if blank.
        ignored_fields: DASH-style field names skipped during compare;
            ``[]`` if blank.
        expected_sql_override: Filename of an override SQL file; ``""``
            means auto-derive from the record-type name.
        cardinality_override: ED-S4 SQL-side cardinality override. The
            reconciliation YAML's ``record_types.<name>.cardinality``
            field describes the SQL-rowset shape (how many SQL rows
            match the driver join), which can differ from the
            ``MultiRecord_<FILETYPE>`` sheet's ``cardinality`` (which
            describes the FILE rowset shape — how many physical rows
            of this record type appear per driver record). When
            non-empty this value overrides the
            ``MultiRecordRow.cardinality`` lookup the emitter would
            otherwise use. Allowed values match the
            :class:`MultiRecordRow.cardinality` literal set
            (``one_per_driver_row`` /  ``many_per_driver_row`` /
            ``zero_or_one_per_driver_row``). ``""`` -> defer to the
            MultiRecord sheet's value.
    """

    record_type_name: str
    key_columns: list[str]
    staging_table: str
    predicate: str
    ignored_fields: list[str]
    expected_sql_override: str
    cardinality_override: str = ""


@dataclass(frozen=True)
class ReconciliationSheet:
    """A complete ``Reconciliation_<FILETYPE>`` sheet.

    Attributes:
        file_type: Extracted from the sheet name suffix (``TRANERT``).
        file_wide_assertions: Pipe-separated assertions from the first
            data row's ``assertions`` cell. ``[]`` if blank.
        rows: Ordered list of reconciliation rows.
    """

    file_type: str
    file_wide_assertions: list[str]
    rows: list[ReconciliationRow]


# ---------------------------------------------------------------------------
# Cross-type rules sheets — workbook-authored cross-record-type validation
# rules for multi-record output files (EC-S8).
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CrossTypeRuleRow:
    """One workbook-authored cross-record-type rule (EC-S8).

    Captures operator-authored cross-record-type assertions that previously
    lived as hand-edited overlays inside the umbrella YAML (e.g. the SHAW
    TRANERT ``header_trailer_count`` overlay on ``ITM-CNT-BRT``). EC-S4's
    mapping emitter consumes this row and emits the umbrella YAML's
    ``cross_type_rules:`` array entries.

    The column set is the minimal cross-cut of fields the engine's
    :class:`src.config.multi_record_config.CrossTypeRule` model unpacks for
    the rule type currently exercised end-to-end against real SHAW data
    (``header_trailer_count``). Additional engine-supported fields
    (``header_field``, ``detail_field``, ``sum_field``, ``sum_of``,
    ``when_type``, ``requires_type``, ``expected_order``, ``exactly``) are
    accepted as OPTIONAL workbook columns (the EC-S1 validator tolerates
    unknown columns; the EC-S2 reader populates ``extra`` from any present)
    so new rule types can be authored without a schema-version bump.

    Attributes:
        rule_id: Stable identifier (``R001``, ``CT001``). Blank-``rule_id``
            rows are skipped at read time (same convention as
            :class:`RulesRow`).
        check: Rule-type token consumed by
            :class:`src.validators.cross_type_validator.CrossTypeValidator`
            (``header_trailer_count``, ``header_trailer_sum``, etc.). The
            engine dispatches on this verbatim — the workbook value is
            preserved as-is.
        record_type: Record-type key the rule targets (e.g.
            ``batch_header``). Matches a key in the corresponding
            ``MultiRecord_<FILETYPE>`` sheet.
        trailer_field: Field name on ``record_type`` carrying the asserted
            value (e.g. ``ITM-CNT-BRT``). DASH-style preserved verbatim.
            ``""`` if not applicable to the rule type.
        count_of: For ``header_trailer_count`` — which record-type group to
            count (defaults to ``detail`` which the engine treats as
            "every non-header record type"). ``""`` defers to the engine
            default.
        allow_empty_batch: ADR 0013 (Option A) opt-in. ``True`` -> a
            legitimately empty batch (declared count == 0 AND zero detail
            rows) is treated as valid; truncated files still fail.
            ``False`` (default) preserves the legacy strict behaviour.
        severity: ``error`` / ``warning``. ``""`` defers to the engine
            default (``error``).
        message: Custom violation message template. May reference
            ``{header_value}`` and ``{actual_count}`` placeholders the
            engine fills in. ``""`` defers to the engine default.
        enabled: ``Y``/``Yes``/``True``/``1`` is truthy; defaults to
            enabled when blank. The mapping emitter SKIPS rows whose
            ``enabled`` is explicitly false so an operator can soft-disable
            a rule without deleting the row.
        extra: Dict of any additional cells the workbook carries beyond
            the canonical column set. EC-S4 merges this dict into the
            emitted YAML entry so rule types that need fields not yet
            promoted to canonical columns (``header_field``, ``sum_of``,
            ``expected_order``, etc.) round-trip cleanly. Blank cells are
            NOT included.
    """

    rule_id: str
    check: str
    record_type: str
    trailer_field: str
    count_of: str
    allow_empty_batch: bool
    severity: str
    message: str
    enabled: bool
    extra: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class CrossTypeRulesSheet:
    """A complete ``CrossTypeRules_<FILETYPE>`` sheet (EC-S8).

    Attributes:
        file_type: Extracted from the sheet name suffix (``TRANERT``).
        rows: Ordered list of cross-type rule rows. Rows whose ``rule_id``
            cell was blank are skipped at read time and never reach this
            list.
    """

    file_type: str
    rows: list[CrossTypeRuleRow]


# ---------------------------------------------------------------------------
# Mapping sheets — column set matches scripts/bulk_convert_mappings.py and
# src/config/template_converter.py exactly. Every cell is preserved as a
# string (or ``None``); EC-S4 does the int/format coercion in one place.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class MappingFieldRow:
    """One field row from a ``*_Mapping`` sheet.

    The column set matches the existing
    ``src/config/template_converter.TemplateConverter`` so the EC-S4
    emitter can re-use the same downstream converter without adapter
    code.

    All values are stored as the raw cell string (or ``None`` if blank)
    so EC-S2 does NOT lose precision. The emitter applies type coercion
    (int for ``Position``/``Length``, bool for ``Required``, etc.) in one
    place where it can also report cell-addressable errors.

    Attributes:
        field_name: DASH-style canonical name (``LN-NUM-ERT``). Preserved
            verbatim — never snake-cased.
        data_type: Free-text type marker (``String``, ``Numeric``,
            ``Date``, ``Decimal``).
        position: 1-indexed start column for fixed-width fields; ``None``
            if not fixed-width or blank.
        length: Field length in characters; ``None`` if blank.
        target_name: Snake-case SQL column alias if the BA provided one;
            ``None`` if blank.
        required: Raw cell text (``Y``/``Yes``/``True``/``1`` is truthy);
            ``None`` if blank. Coerced to bool by EC-S4.
        format: Format hint (``9(5)``, ``MM/DD/CCYY``); ``None`` if blank.
        transformation: Free-text transformation rule (``Default to '100'``);
            ``None`` if blank.
        valid_values: Pipe- or comma-separated allowed values; ``None``
            if blank. NOT parsed here — EC-S4 handles the descriptive-text
            filter via the existing converter's ``_is_descriptive_text``.
        description: Free-text description; ``None`` if blank.
        reconciliation: ED-S4 BA-curation flag. When ``True`` the field
            is included in the per-record-type ``Reconciliation_<FT>``
            YAML's ``record_types.<name>.fields[]`` array AND in the
            corresponding ``expected_*.sql`` SELECT column list. When
            ``False`` (the default for blank cells) the field is
            excluded from BOTH artefacts. Defaults to ``False`` so a
            pre-ED-S4 workbook (no ``Reconciliation`` column) preserves
            the legacy "emit all fields" behaviour via the emitter's
            opt-in convention: if NO row on a sheet flags ``True``, the
            emitter falls back to projecting every row (the ED-S1/ED-S2
            shape). Once any row flips ``True`` the emitter switches to
            curated-subset mode.
        reconciliation_order: ED-S4 emission-order hint. ``0`` (default)
            means "use the workbook row order" — pre-ED-S4 workbooks
            and workbooks that flag rows with a plain ``True`` get
            this. A positive integer N means "emit this field at
            position N in the reconciliation YAML / SQL projection";
            ties are broken by the row's position in the sheet.
            Always paired with ``reconciliation = True`` — a non-zero
            order on an unflagged row is ignored. The
            ``build_shaw_onboarding_workbook`` reverse-engineer step
            populates this from the committed ``tranert.yml`` field
            order so the round-trip reconciliation YAML byte-matches.
        reconciliation_column: Optional override for the
            ``expected_column`` in the reconciliation YAML's
            ``fields[]`` entry. Default empty -> the emitter derives
            the SQL column name from ``target_name`` (upper-cased) per
            the EC-S4 fallback. Set this when the BA has hand-curated
            a column name that differs from the mapping's
            ``target_name`` (e.g. SHAW TRANERT rt_32025 lists
            ``expected_column: ORG_LVL_NUM6_COD`` while the mapping's
            ``target_name`` is ``org_lvl_num_6_cod`` — the underscore
            count differs).
        reconciliation_predicate: Optional per-field SQL predicate
            attached to this field's reconciliation YAML entry. Default
            empty -> no per-field predicate. Used by SHAW TRANERT
            rt_32010's ``OGL-NTE-DAT-ORI`` entry which carries
            ``predicate: "CHG_OFF_CD = '1'"`` to filter only
            charge-off rows.
        reconciliation_sql_expression: Optional override for the
            Oracle SELECT-list expression on this column (the LHS of
            the ``AS`` keyword). Default empty -> the SQL emitter
            derives the expression from ``data_type`` + ``format``
            (TRIM for string, TO_CHAR for date, LPAD/LTRIM for
            numerics). The BA sets this for hand-curated cases where
            the default-derived expression diverges from the
            committed SQL — e.g. SHAW TRANERT batch_header uses
            ``TRIM(t.BK_NUM_BRT)`` for the bank number (decimal 9(5))
            while the ED-S2 default would emit
            ``LPAD(TO_CHAR(t.BK_NUM_BRT), 5, '0')``.
    """

    field_name: str
    data_type: str
    position: int | None
    length: int | None
    target_name: str | None
    required: str | None
    format: str | None
    transformation: str | None
    valid_values: str | None
    description: str | None
    reconciliation: bool = False
    reconciliation_order: int = 0
    reconciliation_column: str = ""
    reconciliation_predicate: str = ""
    reconciliation_sql_expression: str = ""


@dataclass(frozen=True)
class MappingSheet:
    """A complete ``*_Mapping`` sheet.

    Attributes:
        sheet_name: Exact sheet name as written in the workbook (possibly
            shortened with ``~`` per the EC-S1 convention). This is the
            key downstream emitters use to cross-reference from
            ``InputFileSpec.mapping_sheet`` / ``OutputFileSpec.mapping_sheet`` /
            ``MultiRecordRow.mapping_sheet``.
        rows: Ordered list of field rows.
    """

    sheet_name: str
    rows: list[MappingFieldRow]


# ---------------------------------------------------------------------------
# Rules sheets — column set matches src/config/ba_rules_template_converter.py.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RulesRow:
    """One rule row from a ``*_Rules`` sheet.

    The column set matches the existing
    ``src/config/ba_rules_template_converter.BARulesTemplateConverter`` so
    EC-S5 can re-use the same downstream converter without adapter code.

    Every value is preserved as the raw cell string (or ``None`` if blank).
    EC-S5 handles rule-type mapping, value parsing, and severity coercion
    in one place.

    Attributes:
        rule_id: Stable rule identifier (``R001``, ``R002``).
        rule_name: Human-readable rule name; ``None`` if blank.
        field: DASH-style field name the rule applies to. For cross-row
            rules this may carry the ``KEY>TARGET`` or ``FIELD1|FIELD2``
            syntax — preserved verbatim and parsed downstream.
        rule_type: BA-friendly rule type token (``not_empty``, ``numeric``,
            ``exact_length``, ``valid_values``, ``cross_row:unique``,
            ``cross_field``, ``allowed values``, ``range``, ``length``,
            ``regex``, ``date format``).
        severity: ``error``, ``warning``, etc.; ``None`` if blank.
        enabled: ``Y``/``Yes``/``True``/``1`` truthy; ``None`` if blank.
            Coerced to bool by EC-S5.
        message: Free-text user-facing message; ``None`` if blank.
        expected_values: Pipe- or comma-separated values, or
            ``min..max`` ranges, or regex patterns, or date-format codes.
            Interpretation depends on ``rule_type``; ``None`` if blank.
        condition: Optional condition expression (the legacy
            ``Condition (optional)`` column); ``None`` if blank.
        notes: Optional notes column; ``None`` if blank.
    """

    rule_id: str
    rule_name: str | None
    field: str
    rule_type: str
    severity: str | None
    enabled: str | None
    message: str | None
    expected_values: str | None
    condition: str | None
    notes: str | None


@dataclass(frozen=True)
class RulesSheet:
    """A complete ``*_Rules`` sheet.

    Attributes:
        sheet_name: Exact sheet name as written in the workbook.
        rows: Ordered list of rule rows. Rows whose ``rule_id`` cell is
            blank are skipped at read time (matches the existing converter
            behaviour) and never reach this list.
    """

    sheet_name: str
    rows: list[RulesRow]


# ---------------------------------------------------------------------------
# Top-level container — the dataclass tree returned by WorkbookReader.read().
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class OnboardingWorkbook:
    """The complete parsed onboarding workbook.

    The top-level container the EC-S2 reader returns. Downstream emitters
    consume this object and never re-open the ``.xlsx`` file.

    Attributes:
        source: The single ``SourceInfo`` row.
        input_files: All rows from the ``InputFiles`` sheet (ordered).
        output_files: All rows from the ``OutputFiles`` sheet (ordered).
        multi_record_sheets: Keyed by ``file_type`` (the suffix after
            ``MultiRecord_``). Iteration order follows workbook order.
        reconciliation_sheets: Keyed by ``file_type`` (the suffix after
            ``Reconciliation_``).
        cross_type_rules_sheets: Keyed by ``file_type`` (the suffix after
            ``CrossTypeRules_``). Optional — multi-record output files
            without cross-record-type assertions have no entry. EC-S4
            consumes this dict to populate the umbrella YAML's
            ``cross_type_rules:`` array.
        mapping_sheets: Keyed by exact sheet name as written in the
            workbook. Lookups from ``InputFileSpec.mapping_sheet``,
            ``OutputFileSpec.mapping_sheet``, and
            ``MultiRecordRow.mapping_sheet`` all key into this dict.
        rules_sheets: Keyed by exact sheet name; lookups from
            ``OutputFileSpec.rules_sheet`` and ``MultiRecordRow.rules_sheet``
            key into this dict (blank/``"(umbrella)"`` values do NOT
            resolve here — emitters check for those sentinels first).
    """

    source: SourceInfo
    input_files: list[InputFileSpec] = field(default_factory=list)
    output_files: list[OutputFileSpec] = field(default_factory=list)
    multi_record_sheets: dict[str, MultiRecordSheet] = field(default_factory=dict)
    reconciliation_sheets: dict[str, ReconciliationSheet] = field(default_factory=dict)
    cross_type_rules_sheets: dict[str, CrossTypeRulesSheet] = field(
        default_factory=dict
    )
    mapping_sheets: dict[str, MappingSheet] = field(default_factory=dict)
    rules_sheets: dict[str, RulesSheet] = field(default_factory=dict)


__all__ = [
    "WorkbookReadError",
    "SourceInfo",
    "InputFileSpec",
    "OutputFileSpec",
    "MultiRecordRow",
    "MultiRecordSheet",
    "ReconciliationRow",
    "ReconciliationSheet",
    "CrossTypeRuleRow",
    "CrossTypeRulesSheet",
    "MappingFieldRow",
    "MappingSheet",
    "RulesRow",
    "RulesSheet",
    "OnboardingWorkbook",
]
