"""Render a multi-record validation result as a navigable HTML report set.

The single-record :class:`~src.reports.renderers.validation_renderer.ValidationReporter`
generates rich per-file HTML reports for results coming out of
``run_validate_service``. The multi-record validator
(``run_multi_record_validate_service``) returns a top-level dict
with ``record_type_results`` keyed by logical record-type name, and
each value is exactly the single-record result shape that
``ValidationReporter`` already knows how to render. This script wraps
both — it writes:

1. One subpage per record type whose group is non-empty, generated by
   :class:`ValidationReporter` so it benefits from the existing PII
   redaction, charts, and CSV sidecars.
2. A top-level umbrella page that summarises the overall verdict,
   total rows, cross-type violations, and a per-record-type table
   linking out to each subpage.

Lives in ``scripts/`` rather than ``src/`` because the L1 pipeline
gate currently consumes the raw result dict via the runner and does
not require an HTML artifact. Operators / BAs running ad-hoc smoke
tests want a browser-openable view of the verdict; this script
provides that without crossing the ``src/`` discipline line.

Usage (from repo root):

    python scripts/render_multi_record_html.py \\
        --umbrella config/mappings/SHAW_ATOCTRAN.yaml \\
        --file     data/samples/atoctran_shaw_20260514.txt \\
        --output   reports/smoke/SHAW_ATOCTRAN

The output directory will contain ``index.html`` (umbrella) plus one
``<record_type>.html`` per record type that had rows.
"""

from __future__ import annotations

import argparse
import html
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

import yaml

# Make ``src`` importable when invoked from repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.config.multi_record_config import MultiRecordConfig  # noqa: E402
from src.reports.renderers.validation_renderer import ValidationReporter  # noqa: E402
from src.validators.multi_record_validator import MultiRecordValidator  # noqa: E402


# ---------------------------------------------------------------------------
# Umbrella page template
# ---------------------------------------------------------------------------

_UMBRELLA_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       margin: 24px; color: #222; }
h1 { color: #1f3a5f; margin-bottom: 4px; }
.timestamp { color: #666; font-size: 0.9em; margin-bottom: 24px; }
.verdict { display: inline-block; padding: 6px 16px; border-radius: 4px;
           font-weight: 600; font-size: 1.1em; margin: 12px 0 24px 0; }
.verdict.pass { background: #d4edda; color: #155724; }
.verdict.fail { background: #f8d7da; color: #721c24; }
.summary { background: #f4f6f9; padding: 16px 20px; border-radius: 6px;
           margin: 16px 0 24px 0; }
.summary-item { margin: 6px 0; }
.summary-item strong { color: #1f3a5f; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #dde3ea; padding: 10px 12px; text-align: left;
         vertical-align: top; }
th { background-color: #1f3a5f; color: white; }
tr.row-skipped td { color: #888; font-style: italic; }
tr.row-fail td { background: #fff3f4; }
tr.row-pass td { background: #f4faf5; }
a { color: #1f6fb5; text-decoration: none; }
a:hover { text-decoration: underline; }
.cross-type { background: #fff3cd; border-left: 4px solid #856404;
              padding: 12px 16px; margin: 16px 0; border-radius: 4px; }
.cross-type ul { margin: 8px 0 0 0; padding-left: 24px; }
.footer { color: #888; font-size: 0.85em; margin-top: 32px;
          border-top: 1px solid #eee; padding-top: 12px; }
"""


def _verdict_class(valid: bool) -> str:
    """Return the CSS class for the top-level verdict badge."""
    return "pass" if valid else "fail"


def _verdict_label(valid: bool) -> str:
    """Return the verdict badge text."""
    return "PASS" if valid else "FAIL"


def _row_class(value: Dict[str, Any]) -> str:
    """Return the CSS row class based on a record-type result dict."""
    if value.get("skipped") or value.get("total_rows", 0) == 0:
        return "row-skipped"
    return "row-pass" if value.get("valid", True) else "row-fail"


def _format_int(n: Any) -> str:
    """Render an int with thousands separators; return ``-`` for ``None``."""
    if n is None:
        return "-"
    try:
        return f"{int(n):,}"
    except (TypeError, ValueError):
        return str(n)


def _render_umbrella(
    result: Dict[str, Any],
    subpage_names: Dict[str, str],
    umbrella_path: Path,
    file_path: str,
    config_path: str,
) -> None:
    """Render the umbrella index.html linking to each per-record-type page.

    Args:
        result: Output dict from ``MultiRecordValidator.validate``.
        subpage_names: Map from record-type name to subpage filename
            (relative to the umbrella path). Entries are present only
            for record types that had rows.
        umbrella_path: Destination path for the umbrella ``index.html``.
        file_path: Source data file path (for the summary block).
        config_path: Source umbrella YAML path (for the summary block).
    """
    valid = bool(result.get("valid"))
    total_rows = result.get("total_rows", 0)
    cross_type = result.get("cross_type_violations", []) or []
    rtr = result.get("record_type_results", {}) or {}

    # Per-record-type table rows.
    table_rows_html = []
    for type_name in sorted(rtr.keys()):
        row = rtr[type_name]
        skipped = row.get("skipped")
        link_cell = (
            f'<a href="{html.escape(subpage_names[type_name])}">details</a>'
            if type_name in subpage_names
            else "—"
        )
        verdict_cell = "PASS" if row.get("valid", True) else "FAIL"
        if skipped:
            verdict_cell = f"skipped ({html.escape(skipped)})"
        table_rows_html.append(
            f'<tr class="{_row_class(row)}">'
            f"<td>{html.escape(type_name)}</td>"
            f"<td>{_format_int(row.get('total_rows', row.get('row_count')))}</td>"
            f"<td>{_format_int(row.get('valid_rows'))}</td>"
            f"<td>{_format_int(row.get('error_count'))}</td>"
            f"<td>{_format_int(row.get('warning_count'))}</td>"
            f"<td>{verdict_cell}</td>"
            f"<td>{link_cell}</td>"
            "</tr>"
        )
    table_html = "\n".join(table_rows_html)

    # Cross-type violations block.
    if cross_type:
        items = "".join(
            "<li>"
            f"<strong>{html.escape(str(v.get('rule_id', '')))}</strong>: "
            f"{html.escape(str(v.get('message', '')))}"
            "</li>"
            for v in cross_type[:50]
        )
        more = (
            f"<p>… and {len(cross_type) - 50} more</p>"
            if len(cross_type) > 50
            else ""
        )
        cross_type_html = (
            '<div class="cross-type">'
            f"<strong>Cross-type violations ({len(cross_type)}):</strong>"
            f"<ul>{items}</ul>{more}"
            "</div>"
        )
    else:
        cross_type_html = (
            '<div class="cross-type" style="background:#e6f4ea;'
            'border-left-color:#1e8e3e;color:#1e4620;">'
            "<strong>No cross-type violations.</strong>"
            "</div>"
        )

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    body = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Valdo Multi-Record Validation Report</title>
<style>{_UMBRELLA_CSS}</style>
</head>
<body>
<h1>Valdo Multi-Record Validation Report</h1>
<p class="timestamp">Generated: {timestamp}</p>

<div class="verdict {_verdict_class(valid)}">{_verdict_label(valid)}</div>

<div class="summary">
<div class="summary-item"><strong>Data file:</strong> {html.escape(file_path)}</div>
<div class="summary-item"><strong>Umbrella config:</strong> {html.escape(config_path)}</div>
<div class="summary-item"><strong>Total rows:</strong> {_format_int(total_rows)}</div>
<div class="summary-item"><strong>Record types configured:</strong> {len(rtr)}</div>
<div class="summary-item"><strong>Record types with rows:</strong> {len(subpage_names)}</div>
<div class="summary-item"><strong>Cross-type violations:</strong> {len(cross_type)}</div>
</div>

{cross_type_html}

<h2>Per-record-type results</h2>
<table>
<tr>
<th>Record type</th>
<th>Rows</th>
<th>Valid rows</th>
<th>Errors</th>
<th>Warnings</th>
<th>Verdict</th>
<th>Details</th>
</tr>
{table_html}
</table>

<p class="footer">
Generated by <code>scripts/render_multi_record_html.py</code>.
Per-record-type subpages produced via
<code>src.reports.renderers.validation_renderer.ValidationReporter</code>
with PII redaction enabled by default.
</p>
</body>
</html>
"""

    umbrella_path.write_text(body, encoding="utf-8")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def render(
    umbrella_yaml_path: str,
    data_file_path: str,
    output_dir: str,
    suppress_pii: bool = True,
) -> Path:
    """Validate a multi-record file and render a full HTML report set.

    Args:
        umbrella_yaml_path: Path to the multi-record umbrella YAML.
        data_file_path: Path to the data file to validate.
        output_dir: Directory to write the report set into. Created if
            it does not exist.
        suppress_pii: Whether to redact raw field values from per-record
            subpages. Mirrors the ``ValidationReporter.generate`` flag.
            Defaults to True (safer).

    Returns:
        Path to the umbrella ``index.html`` that links to all subpages.
    """
    umbrella_path = Path(umbrella_yaml_path)
    data_path = Path(data_file_path)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(umbrella_path, encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)
    cfg = MultiRecordConfig(**raw)

    result = MultiRecordValidator().validate(str(data_path), cfg)

    # Render one subpage per record type whose group has rows. Empty
    # groups are listed in the umbrella table but get no subpage —
    # ``ValidationReporter`` requires a real result payload with at
    # least the ``errors`` and ``warnings`` keys.
    reporter = ValidationReporter()
    subpage_names: Dict[str, str] = {}
    for type_name, type_result in result.get("record_type_results", {}).items():
        # Skip empty / skipped groups: the result dict won't have the
        # keys the renderer needs and the page would be empty anyway.
        if type_result.get("skipped") or not type_result.get("total_rows"):
            continue
        subpage_filename = f"{type_name}.html"
        subpage_path = out_dir / subpage_filename
        reporter.generate(type_result, str(subpage_path), suppress_pii=suppress_pii)
        subpage_names[type_name] = subpage_filename

    umbrella_html_path = out_dir / "index.html"
    _render_umbrella(
        result,
        subpage_names,
        umbrella_html_path,
        file_path=str(data_path),
        config_path=str(umbrella_path),
    )
    return umbrella_html_path


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--umbrella",
        required=True,
        help="Path to the multi-record umbrella YAML config.",
    )
    parser.add_argument(
        "--file",
        required=True,
        help="Path to the data file to validate.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for the HTML report set.",
    )
    parser.add_argument(
        "--no-pii-suppression",
        action="store_true",
        help=(
            "Disable PII redaction in per-record-type subpages. By default "
            "raw field values are replaced with [REDACTED] in error "
            "messages. Use with caution."
        ),
    )
    args = parser.parse_args()

    index_path = render(
        umbrella_yaml_path=args.umbrella,
        data_file_path=args.file,
        output_dir=args.output,
        suppress_pii=not args.no_pii_suppression,
    )
    print(f"Multi-record HTML report written to: {index_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
