-- Oracle DDL (reference)
CREATE TABLE ACCOUNTS (
  ACCOUNT_ID        VARCHAR2(10) PRIMARY KEY,
  CHARGE_OFF_AMT    NUMBER(12,2),
  FIRST_DELQ_DATE   DATE,
  OPENED_DATE       DATE
);

CREATE TABLE CONTACTS (
  CONTACT_ID        VARCHAR2(12) PRIMARY KEY,
  FULL_NAME         VARCHAR2(100)
);

CREATE TABLE ACCOUNT_CONTACTS (
  ACCOUNT_ID        VARCHAR2(10) NOT NULL,
  CONTACT_ID        VARCHAR2(12) NOT NULL,
  RELATIONSHIP_CODE VARCHAR2(20),
  REL_SEQ           NUMBER(3),
  CONSTRAINT PK_ACCOUNT_CONTACTS PRIMARY KEY (ACCOUNT_ID, CONTACT_ID),
  CONSTRAINT FK_ACCT_CONTACTS_ACCT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID),
  CONSTRAINT FK_ACCT_CONTACTS_CONT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID)
);
