-- Oracle source query for multi-transaction output
WITH account_txn AS (
  SELECT '32010' AS TRANSACTION_CODE,
         a.ACCOUNT_ID,
         CAST(NULL AS NUMBER(3)) AS REL_SEQ,
         a.CHARGE_OFF_AMT,
         CAST(NULL AS DATE) AS FIRST_DELQ_DATE,
         'ACCOUNT' AS CONTACT_NAME,
         1 AS ORDER_KEY
  FROM ACCOUNTS a
),
contact_txn AS (
  SELECT '32005' AS TRANSACTION_CODE,
         ac.ACCOUNT_ID,
         ac.REL_SEQ,
         CAST(NULL AS NUMBER(12,2)) AS CHARGE_OFF_AMT,
         CAST(NULL AS DATE) AS FIRST_DELQ_DATE,
         c.FULL_NAME AS CONTACT_NAME,
         2 AS ORDER_KEY
  FROM ACCOUNT_CONTACTS ac
  JOIN CONTACTS c ON c.CONTACT_ID = ac.CONTACT_ID
),
delq_txn AS (
  SELECT '32040' AS TRANSACTION_CODE,
         a.ACCOUNT_ID,
         CAST(NULL AS NUMBER(3)) AS REL_SEQ,
         CAST(NULL AS NUMBER(12,2)) AS CHARGE_OFF_AMT,
         a.FIRST_DELQ_DATE,
         'DELINQUENCY' AS CONTACT_NAME,
         3 AS ORDER_KEY
  FROM ACCOUNTS a
)
SELECT TRANSACTION_CODE,
       ACCOUNT_ID,
       REL_SEQ,
       CHARGE_OFF_AMT,
       TO_CHAR(FIRST_DELQ_DATE,'YYYYMMDD') AS FIRST_DELQ_DATE,
       CONTACT_NAME
FROM (
  SELECT * FROM account_txn
  UNION ALL
  SELECT * FROM contact_txn
  UNION ALL
  SELECT * FROM delq_txn
)
ORDER BY ACCOUNT_ID, ORDER_KEY, REL_SEQ DESC;
